main:

  Conference/Workshop TPC:
    
      - title: USENIX Symposium on Vehicle Security and Privacy 2024 2025
        link: https://www.usenix.org/conference/vehiclesec25
      - title: International Workshop on Software Engineering for Autonomous Driving Systems (SE4ADS) 2025
        link: https://conf.researchr.org/home/icse-2025/se4ads-2025
      - title: Network and Distributed System Security (NDSS) Symposium (Artifact Evaluation) 2024
        link: https://www.ndss-symposium.org/ndss2024/submissions/artifacts/

  Journal Reviewers:

      - title: ACM Transactions on Privacy and Security (TOPS)
        link: https://dl.acm.org/journal/tops
      - title: IEEE Transactions on Dependable and Secure Computing (TDSC)
        link: https://www.computer.org/csdl/journal/tq
      - title: ACM Transactions on Software Engineering and Methodology (TOSEM)
        link: https://mc.manuscriptcentral.com/tosem
